export interface DomainExtension {
  id: number;
  ext: string;
  desc: string;
}

export const ALL_100_EXTENSIONS: DomainExtension[] = [
  { id: 1, ext: '.com', desc: 'Global business' },
  { id: 2, ext: '.net', desc: 'Network/tech' },
  { id: 3, ext: '.org', desc: 'Organization' },
  { id: 4, ext: '.io', desc: 'Startup/Tech' },
  { id: 5, ext: '.ai', desc: 'AI projects' },
  { id: 6, ext: '.co', desc: 'Company/Startup' },
  { id: 7, ext: '.app', desc: 'Mobile/Web apps' },
  { id: 8, ext: '.dev', desc: 'Developers' },
  { id: 9, ext: '.tech', desc: 'Technology' },
  { id: 10, ext: '.xyz', desc: 'Modern branding' },
  { id: 11, ext: '.online', desc: 'Online business' },
  { id: 12, ext: '.store', desc: 'Ecommerce' },
  { id: 13, ext: '.shop', desc: 'Shopping' },
  { id: 14, ext: '.site', desc: 'General website' },
  { id: 15, ext: '.website', desc: 'Web presence' },
  { id: 16, ext: '.biz', desc: 'Business' },
  { id: 17, ext: '.info', desc: 'Information' },
  { id: 18, ext: '.me', desc: 'Personal brand' },
  { id: 19, ext: '.pro', desc: 'Professional' },
  { id: 20, ext: '.agency', desc: 'Agencies' },
  { id: 21, ext: '.digital', desc: 'Digital services' },
  { id: 22, ext: '.studio', desc: 'Creative studio' },
  { id: 23, ext: '.media', desc: 'Media company' },
  { id: 24, ext: '.design', desc: 'Designers' },
  { id: 25, ext: '.art', desc: 'Artists' },
  { id: 26, ext: '.blog', desc: 'Blogging' },
  { id: 27, ext: '.news', desc: 'News portal' },
  { id: 28, ext: '.live', desc: 'Live streaming' },
  { id: 29, ext: '.tv', desc: 'Video/media' },
  { id: 30, ext: '.fm', desc: 'Audio/radio' },
  { id: 31, ext: '.cloud', desc: 'Cloud services' },
  { id: 32, ext: '.software', desc: 'Software' },
  { id: 33, ext: '.systems', desc: 'IT systems' },
  { id: 34, ext: '.solutions', desc: 'Business solutions' },
  { id: 35, ext: '.services', desc: 'Service company' },
  { id: 36, ext: '.company', desc: 'Companies' },
  { id: 37, ext: '.world', desc: 'Global branding' },
  { id: 38, ext: '.today', desc: 'Daily updates' },
  { id: 39, ext: '.space', desc: 'Creative projects' },
  { id: 40, ext: '.network', desc: 'Networks' },
  { id: 41, ext: '.finance', desc: 'Finance' },
  { id: 42, ext: '.capital', desc: 'Investment' },
  { id: 43, ext: '.money', desc: 'Financial' },
  { id: 44, ext: '.fund', desc: 'Funds' },
  { id: 45, ext: '.investments', desc: 'Investors' },
  { id: 46, ext: '.bank', desc: 'Banking' },
  { id: 47, ext: '.exchange', desc: 'Crypto/trading' },
  { id: 48, ext: '.crypto', desc: 'Crypto projects' },
  { id: 49, ext: '.coin', desc: 'Coin/token' },
  { id: 50, ext: '.marketing', desc: 'Marketing agency' },
  { id: 51, ext: '.social', desc: 'Social platform' },
  { id: 52, ext: '.community', desc: 'Community' },
  { id: 53, ext: '.events', desc: 'Event management' },
  { id: 54, ext: '.education', desc: 'Education' },
  { id: 55, ext: '.academy', desc: 'Courses' },
  { id: 56, ext: '.school', desc: 'Schools' },
  { id: 57, ext: '.training', desc: 'Training' },
  { id: 58, ext: '.careers', desc: 'Jobs' },
  { id: 59, ext: '.jobs', desc: 'Recruitment' },
  { id: 60, ext: '.works', desc: 'Portfolio' },
  { id: 61, ext: '.team', desc: 'Teams' },
  { id: 62, ext: '.group', desc: 'Groups' },
  { id: 63, ext: '.partners', desc: 'Partnerships' },
  { id: 64, ext: '.ventures', desc: 'Venture capital' },
  { id: 65, ext: '.consulting', desc: 'Consultants' },
  { id: 66, ext: '.law', desc: 'Legal' },
  { id: 67, ext: '.legal', desc: 'Law firms' },
  { id: 68, ext: '.doctor', desc: 'Doctors' },
  { id: 69, ext: '.health', desc: 'Healthcare' },
  { id: 70, ext: '.clinic', desc: 'Clinics' },
  { id: 71, ext: '.fitness', desc: 'Fitness' },
  { id: 72, ext: '.travel', desc: 'Travel' },
  { id: 73, ext: '.tour', desc: 'Tourism' },
  { id: 74, ext: '.vacations', desc: 'Travel packages' },
  { id: 75, ext: '.hotel', desc: 'Hotels' },
  { id: 76, ext: '.restaurant', desc: 'Restaurants' },
  { id: 77, ext: '.cafe', desc: 'Cafes' },
  { id: 78, ext: '.food', desc: 'Food business' },
  { id: 79, ext: '.coffee', desc: 'Coffee brands' },
  { id: 80, ext: '.pizza', desc: 'Food niche' },
  { id: 81, ext: '.fashion', desc: 'Fashion' },
  { id: 82, ext: '.style', desc: 'Style brand' },
  { id: 83, ext: '.beauty', desc: 'Beauty industry' },
  { id: 84, ext: '.photography', desc: 'Photography' },
  { id: 85, ext: '.photos', desc: 'Photo gallery' },
  { id: 86, ext: '.video', desc: 'Video content' },
  { id: 87, ext: '.games', desc: 'Gaming' },
  { id: 88, ext: '.game', desc: 'Gaming projects' },
  { id: 89, ext: '.fun', desc: 'Entertainment' },
  { id: 90, ext: '.vip', desc: 'Premium branding' },
  { id: 91, ext: '.luxury', desc: 'Luxury brands' },
  { id: 92, ext: '.gold', desc: 'Premium niche' },
  { id: 93, ext: '.club', desc: 'Membership' },
  { id: 94, ext: '.center', desc: 'Business center' },
  { id: 95, ext: '.zone', desc: 'Modern branding' },
  { id: 96, ext: '.expert', desc: 'Expert services' },
  { id: 97, ext: '.guru', desc: 'Coaching' },
  { id: 98, ext: '.one', desc: 'Unique branding' },
  { id: 99, ext: '.link', desc: 'Link services' },
  { id: 100, ext: '.global', desc: 'International brand' }
];
